export const pokemons = {
  normal: { name: 'normal', apiNumber: 1 },
  fighting: { name: 'fighting', apiNumber: 2 },
  flying: { name: 'flying', apiNumber: 3 },
  poison: { name: 'poison', apiNumber: 4 },
  ground: { name: 'ground', apiNumber: 5 },
  rock: { name: 'rock', apiNumber: 6 },
  bug: { name: 'bug', apiNumber: 7 },
  ghost: { name: 'ghost', apiNumber: 8 },
  steel: { name: 'steel', apiNumber: 9 },
  fire: { name: 'fire', apiNumber: 10 },
  water: { name: 'water', apiNumber: 11 },
  grass: { name: 'grass', apiNumber: 12 },
  electric: { name: 'electric', apiNumber: 13 },
  psychic: { name: 'psychic', apiNumber: 14 },
  ice: { name: 'ice', apiNumber: 15 },
  dragon: { name: 'dragon', apiNumber: 16 },
  dark: { name: 'dark', apiNumber: 17 },
  fairy: { name: 'fairy', apiNumber: 18 },
};
